"""add total_tokens & total_price to ChatSession

Revision ID: 89f20d74f79a
Revises: fcda8912b421
Create Date: 2026-02-13 15:27:38.733305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89f20d74f79a'
down_revision: Union[str, Sequence[str], None] = 'fcda8912b421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('total_tokens', sa.Integer(), nullable=False))
    op.add_column('chat_sessions', sa.Column('total_price', sa.Numeric(precision=20, scale=12), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'total_price')
    op.drop_column('chat_sessions', 'total_tokens')
    # ### end Alembic commands ###
